name: Daily Drift Check

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"   # 2 AM IST

jobs:
  drift:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up server
        run: curl https://cloud-ml-7g3v.onrender.com

      - name: Wait for server
        run: sleep 30

      - name: Run drift check
        run: curl https://cloud-ml-7g3v.onrender.com/run-drift
